-- Seed: product abbreviations + dialect/phonetic variants exposed by the
-- 2026-06-20 benchmark v2 run (product match was the residual lever at ~50%).
-- These are short forms (vb, gbh, hcl), phonetic spellings (kaplink, girboks),
-- and Gujlish/Hindi product words (atta, kostik, til) that no fuzzy score can
-- bridge to the catalog name — they need an explicit Tier-3 mapping.
--
-- Curation rule: UNAMBIGUOUS terms only. Skipped generic/ambiguous raws that
-- map to multiple products (e.g. "tile", "acid", "maal", "cotton fabric").
-- Conflicts with prior seeds are ignored (partial unique index on the
-- active (term_normalized, industry_segment) pair).

INSERT INTO industry_dictionary (term, term_normalized, canonical, category, industry_segment, language) VALUES
-- ── foundry ──
('vb', 'vb', 'Valve Body', 'product', 'foundry', 'gujlish'),
('valv', 'valv', 'Valve Body', 'product', 'foundry', 'gujlish'),
('gbh', 'gbh', 'Gear Box Housing', 'product', 'foundry', 'gujlish'),
('girboks', 'girboks', 'Gear Box Housing', 'product', 'foundry', 'gujlish'),
('fl', 'fl', 'Flange', 'product', 'foundry', 'gujlish'),
('flej', 'flej', 'Flange', 'product', 'foundry', 'gujlish'),
('cop', 'cop', 'Coupling', 'product', 'foundry', 'gujlish'),
('kaplink', 'kaplink', 'Coupling', 'product', 'foundry', 'gujlish'),
('kapling', 'kapling', 'Coupling', 'product', 'foundry', 'gujlish'),
('bc', 'bc', 'Bearing Cap', 'product', 'foundry', 'gujlish'),
('bering kavar', 'bering kavar', 'Bearing Cap', 'product', 'foundry', 'gujlish'),
('pamp bodi', 'pamp bodi', 'Pump Housing', 'product', 'foundry', 'gujlish'),
('pamp housing', 'pamp housing', 'Pump Housing', 'product', 'foundry', 'gujlish'),
('impellar', 'impellar', 'Impeller', 'product', 'foundry', 'gujlish'),
('brecket', 'brecket', 'Bracket', 'product', 'foundry', 'gujlish'),
-- ── auto_parts ──
('bp', 'bp', 'Brake Pad', 'product', 'auto_parts', 'gujlish'),
('brek', 'brek', 'Brake Pad', 'product', 'auto_parts', 'gujlish'),
('cp', 'cp', 'Clutch Plate', 'product', 'auto_parts', 'gujlish'),
('klach plet', 'klach plet', 'Clutch Plate', 'product', 'auto_parts', 'gujlish'),
('gs', 'gs', 'Gasket Set', 'product', 'auto_parts', 'gujlish'),
('sp', 'sp', 'Spark Plug', 'product', 'auto_parts', 'gujlish'),
('sil', 'sil', 'Oil Seal', 'product', 'auto_parts', 'gujlish'),
('sokar', 'sokar', 'Shock Absorber', 'product', 'auto_parts', 'gujlish'),
('wbr', 'wbr', 'Wheel Bearing', 'product', 'auto_parts', 'gujlish'),
('vil bering', 'vil bering', 'Wheel Bearing', 'product', 'auto_parts', 'gujlish'),
('pandar bering', 'pandar bering', 'Wheel Bearing', 'product', 'auto_parts', 'gujlish'),
('piston', 'piston', 'Piston Ring', 'product', 'auto_parts', 'gujlish'),
-- ── ceramics ──
('ft', 'ft', 'Floor Tile 2x2', 'product', 'ceramics', 'gujlish'),
('flor tail', 'flor tail', 'Floor Tile 2x2', 'product', 'ceramics', 'gujlish'),
('wt', 'wt', 'Wall Tile 1x1', 'product', 'ceramics', 'gujlish'),
('vt', 'vt', 'Vitrified Tile', 'product', 'ceramics', 'gujlish'),
('vitrified', 'vitrified', 'Vitrified Tile', 'product', 'ceramics', 'gujlish'),
('vitrifaid', 'vitrifaid', 'Vitrified Tile', 'product', 'ceramics', 'gujlish'),
('ps', 'ps', 'Porcelain Slab', 'product', 'ceramics', 'gujlish'),
('sleb', 'sleb', 'Porcelain Slab', 'product', 'ceramics', 'gujlish'),
('komod', 'komod', 'Toilet Seat', 'product', 'ceramics', 'gujlish'),
('naliyu', 'naliyu', 'Roof Tile', 'product', 'ceramics', 'gujlish'),
('adhesiv', 'adhesiv', 'Tile Adhesive', 'product', 'ceramics', 'gujlish'),
('tail nu gund', 'tail nu gund', 'Tile Adhesive', 'product', 'ceramics', 'gujlish'),
('vos besin', 'vos besin', 'Wash Basin', 'product', 'ceramics', 'gujlish'),
('basin', 'basin', 'Wash Basin', 'product', 'ceramics', 'gujlish'),
-- ── chemicals ──
('hcl', 'hcl', 'Hydrochloric Acid', 'product', 'chemicals', 'gujlish'),
('h2so4', 'h2so4', 'Sulphuric Acid', 'product', 'chemicals', 'gujlish'),
('salfurik esid', 'salfurik esid', 'Sulphuric Acid', 'product', 'chemicals', 'gujlish'),
('naoh', 'naoh', 'Caustic Soda', 'product', 'chemicals', 'gujlish'),
('kostik', 'kostik', 'Caustic Soda', 'product', 'chemicals', 'gujlish'),
('kostik soda', 'kostik soda', 'Caustic Soda', 'product', 'chemicals', 'gujlish'),
('epoksi', 'epoksi', 'Epoxy Resin', 'product', 'chemicals', 'gujlish'),
('fevikol', 'fevikol', 'Adhesive', 'product', 'chemicals', 'gujlish'),
('gund', 'gund', 'Adhesive', 'product', 'chemicals', 'gujlish'),
('kaach', 'kaach', 'Sodium Silicate', 'product', 'chemicals', 'gujlish'),
('pigment', 'pigment', 'Pigment Red', 'product', 'chemicals', 'gujlish'),
('sol', 'sol', 'Solvent', 'product', 'chemicals', 'gujlish'),
-- ── diamond ──
('ml', 'ml', 'Melee Diamonds', 'product', 'diamond', 'gujlish'),
('melee', 'melee', 'Melee Diamonds', 'product', 'diamond', 'gujlish'),
('pd', 'pd', 'Polished Diamond', 'product', 'diamond', 'gujlish'),
('polish heera', 'polish heera', 'Polished Diamond', 'product', 'diamond', 'gujlish'),
('raf heera', 'raf heera', 'Rough Diamond 1ct', 'product', 'diamond', 'gujlish'),
('gc', 'gc', 'Gold Chain 22K', 'product', 'diamond', 'gujlish'),
('sr', 'sr', 'Silver Ring', 'product', 'diamond', 'gujlish'),
('chandi n ring', 'chandi n ring', 'Silver Ring', 'product', 'diamond', 'gujlish'),
('ks', 'ks', 'Kundan Set', 'product', 'diamond', 'gujlish'),
('kundan', 'kundan', 'Kundan Set', 'product', 'diamond', 'gujlish'),
('pendant', 'pendant', 'Diamond Pendant', 'product', 'diamond', 'gujlish'),
('heera nu pendant', 'heera nu pendant', 'Diamond Pendant', 'product', 'diamond', 'gujlish'),
('chudi', 'chudi', 'Gold Bangles', 'product', 'diamond', 'gujlish'),
('sitter bangdi', 'sitter bangdi', 'Gold Bangles', 'product', 'diamond', 'gujlish'),
-- ── food_processing ──
('ghi', 'ghi', 'Pure Ghee', 'product', 'food_processing', 'gujlish'),
('ghee', 'ghee', 'Pure Ghee', 'product', 'food_processing', 'gujlish'),
('haldar', 'haldar', 'Turmeric Powder', 'product', 'food_processing', 'gujlish'),
('hldi', 'hldi', 'Turmeric Powder', 'product', 'food_processing', 'gujlish'),
('jira', 'jira', 'Cumin Seeds', 'product', 'food_processing', 'gujlish'),
('jiru', 'jiru', 'Cumin Seeds', 'product', 'food_processing', 'gujlish'),
('lal marcha', 'lal marcha', 'Chilli Powder', 'product', 'food_processing', 'gujlish'),
('marcha paudar', 'marcha paudar', 'Chilli Powder', 'product', 'food_processing', 'gujlish'),
('keri nu athanu', 'keri nu athanu', 'Pickle Mango', 'product', 'food_processing', 'gujlish'),
('popod', 'popod', 'Papad', 'product', 'food_processing', 'gujlish'),
('mixture', 'mixture', 'Namkeen Mix', 'product', 'food_processing', 'gujlish'),
-- ── pharma ──
('pcm', 'pcm', 'Paracetamol 500mg', 'product', 'pharma', 'gujlish'),
('amoksilin', 'amoksilin', 'Amoxicillin 250mg', 'product', 'pharma', 'gujlish'),
('moks', 'moks', 'Amoxicillin 250mg', 'product', 'pharma', 'gujlish'),
('ors', 'ors', 'ORS Powder', 'product', 'pharma', 'gujlish'),
('detol', 'detol', 'Antiseptic Liquid', 'product', 'pharma', 'gujlish'),
('malham', 'malham', 'Pain Relief Ointment', 'product', 'pharma', 'gujlish'),
('dard ni malham', 'dard ni malham', 'Pain Relief Ointment', 'product', 'pharma', 'gujlish'),
('kuf sirap', 'kuf sirap', 'Cough Syrup', 'product', 'pharma', 'gujlish'),
('khansi ni dava', 'khansi ni dava', 'Cough Syrup', 'product', 'pharma', 'gujlish'),
('patti', 'patti', 'Bandage Roll', 'product', 'pharma', 'gujlish'),
-- ── plastics ──
('hdpe', 'hdpe', 'HDPE Sheet', 'product', 'plastics', 'gujlish'),
('hde sit', 'hde sit', 'HDPE Sheet', 'product', 'plastics', 'gujlish'),
('pvc', 'pvc', 'PVC Pipe 4 inch', 'product', 'plastics', 'gujlish'),
('paip', 'paip', 'PVC Pipe 4 inch', 'product', 'plastics', 'gujlish'),
('dana', 'dana', 'PP Granules', 'product', 'plastics', 'gujlish'),
('film', 'film', 'LDPE Film', 'product', 'plastics', 'gujlish'),
('dabba', 'dabba', 'Plastic Container', 'product', 'plastics', 'gujlish'),
('kontainer', 'kontainer', 'Plastic Container', 'product', 'plastics', 'gujlish'),
('bmb', 'bmb', 'Blow Mould Bottle', 'product', 'plastics', 'gujlish'),
('bottal', 'bottal', 'Blow Mould Bottle', 'product', 'plastics', 'gujlish'),
('masterb ech', 'masterb ech', 'Master Batch Black', 'product', 'plastics', 'gujlish'),
('mold part', 'mold part', 'Injection Mould Part', 'product', 'plastics', 'gujlish'),
-- ── textiles ──
('dm', 'dm', 'Dress Material', 'product', 'textiles', 'gujlish'),
('jakard', 'jakard', 'Jacquard Fabric', 'product', 'textiles', 'gujlish'),
('viscos', 'viscos', 'Viscose Fabric', 'product', 'textiles', 'gujlish'),
('viskos', 'viskos', 'Viscose Fabric', 'product', 'textiles', 'gujlish'),
('les', 'les', 'Lace Border', 'product', 'textiles', 'gujlish'),
('bordar', 'bordar', 'Lace Border', 'product', 'textiles', 'gujlish'),
('les bordar', 'les bordar', 'Lace Border', 'product', 'textiles', 'gujlish'),
('saree', 'saree', 'Polyester Saree', 'product', 'textiles', 'gujlish')
ON CONFLICT (term_normalized, industry_segment) WHERE is_active = TRUE DO NOTHING;
